import:
    write: yes
    copy: yes
    move: no
    link: no
    delete: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    none_rec_action: ask
    timid: no
    autotag: yes
    quiet: no
    singletons: no
    default_action: apply
    languages: []
    detail: no
    flat: no
    group_albums: no
    pretend: no
    search_ids: []
    duplicate_action: ask

clutter: [Thumbs.DB, .DS_Store]
ignore:
    - .*
    - '*~'
    - System Volume Information
    - lost+found
ignore_hidden: yes

replace:
    '[\\/]': '-'
    ^\.: _
    '[\x00-\x1f]': _
    '[<>"\?\*\|]': _
    ':': ' -'
    \s+$: ''
    ^\s+: ''
path_sep_replace: _
asciify_paths: no
art_filename: cover
max_filename_length: 0

plugins:
    - inline
    - mbcollection
    - chroma
    - fromfilename
    - info
    - duplicates
    - edit
    - fetchart
    - ipfs
    - lastgenre
    - missing
    - mbsync
    - mpdstats
    - mpdupdate
    - lyrics
    - playlist
    - smartplaylist
    - replaygain
    # Suggested upstream at https://github.com/beetbox/beets/pull/4748,
    # currently relies upon a symlink to:
    # ~/repos/beets-import_history/beetsplug
    - importhistory
    # merged upstream, but not yet released:
    # https://github.com/beetbox/beets/pull/4807, available in my nixos-configs
    # overlays
    - mbsubmit
    - check
pluginpath: 
    - /home/doron/repos/beets-import_history/beetsplug
    - /home/doron/repos/beets-check/beetsplug
threaded: yes
timeout: 5.0
per_disc_numbering: yes
verbose: 0
terminal_encoding:
original_date: no
id3v23: no
va_name: Various Artists

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

format_item: ${format} % ${albumartist} - ${album} | CD-${disc} | ${track} ${title}
format_album: $album
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no

sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes
item_fields:
    isMultiDisc: |
        u'yes' if
            (int(disctotal) > 1) and (disctotal != '')
        else
            u''

paths:
    default: $album%aunique{album, albumartist}/%if{$isMultiDisc,CD-$disc/}$track $title
    singleton: $artist - Singles/$title
    comp: $album%aunique{album, albumartist}/%if{$isMultiDisc,CD-$disc/}$track $title

musicbrainz:
    host: musicbrainz.org
    ratelimit: 1
    ratelimit_interval: 1.0
    searchlimit: 10
    user: doronbehar

chrome:
    auto: no

ipfs:
    auto: no

lastgenre:
    force: no
    source: track
    count: 10

match:
    # Consider every match above 90% good enough for sparing the questions
    # https://beets.readthedocs.io/en/stable/reference/config.html#autotagger-matching-options
    strong_rec_thresh: 0.10
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    track_length_grace: 10
    track_length_max: 30

lyrics:
    sources: google musixmatch
    # Takes too much network resources for not being particularly important
    auto: no

replaygain:
    backend: gstreamer

include:
    - private.yaml
